name: FTP Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    name: FTP Deployment
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install PHP and Composer
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, pdo, pdo_mysql, intl, gd, bcmath, zip
        tools: composer

    - name: Install Composer Dependencies
      run: composer install --no-dev --optimize-autoloader

    - name: Build Frontend
      run: |
        npm install
        npm run build

    - name: Deploy to FTP (Hostinger)
      uses: SamKirkland/FTP-Deploy-Action@v4.3.3
      with:
        server: thesavants.in
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /public_html/
        local-dir: ./public/build # Deploy the build folder
        timeout: 7200
        exclude: |
          vendor/**
          node_modules/**
          .env
          storage/**

    - name: Clear Laravel Cache
      run: |
        php artisan config:clear
        php artisan cache:clear
        php artisan view:clear

    - name: Set Correct Permissions
      run: chmod -R 755 ./public_html/build
